public static class YesJaden{
public static string[] Phrases = {
"How Can Mirrors Be Real If Our Eyes Aren't Real",
"I Am Not A Human And I Don't Speak English",
"The Biggest Flex Anyone Will Ever Have Is Dying.",
"If A Cup Cake Falls From A Tree How Far Away Will It Be From Down. #Jupiter",
"The More Time You Spend Awake The More Time You Spend Asleep.",
"I Only Skate When I Have Emotional Trauma",
"A lot Of My Tweets Will Come True In 2018",
"como os espelhos podem ser reais se nossos olhos não são reais",
"Jealousy Just Reassures Your Love.",
"You Do Not Know Who You Are Or Why Your Here So When You See Someone Who Dose The Society Comes Together As A Whole And Destroys Them.",
"To The Artist Of This Coming Generation And Of The Renaissance. The People That Truly Understand Your Art are The People Who Don't Comment",
"I Encourage You All To Unfollow Me So I Can Be Left With The People Who Actually Appreciate Philosophy And Poetry. #CoolTapeVol2",
"We Need To Stop Teaching The Youth About The Past And Encourage Them To Change The Future.",
"There Is No Nutrients In Our Food Anymore Or In Our Soil OR IN OUR WATER.",
"I Should Just Stop Tweeting, The Human Consciousness Must Raise Before I Speak My Juvenile Philosophy. Shouts Out To @TIME",
"The Great Gatsby Is One Of The Greatest Movies Of All Time, Coachella.",
"Everybody Get Off Your Phones And Go Do What You Actually Wanna Do",
"If Everybody In The World Dropped Out Of School We Would Have A Much More Intelligent Society.",
"If Newborn Babies Could Speak They Would Be The Most Intelligent Beings On Planet Earth.",
"Education Is Rebellion.",
"School Is The Tool To Brainwash The Youth.",
"People Use To Ask Me What Do You Wanna Be When You Get Older And I Would Say What A Stupid Question The Real Question Is What Am I Right Now",
"If A Book Store Never Runs Out Of A Certain Book, Dose That Mean That Nobody Reads It, Or Everybody Reads It",
"\"It's Your Birthday\" Mateo Said. I Didn't Respond. \"Are You Not Excited To Be 15\" He Asked. Reading My Book I Uttered \"I Turned 15 Long Ago\"",
"I Honestly Love When People Hate Even When There Close To You.",
"Ill Never Forget The Blogs That Believed In Me Since The Begging.",
"I Only Apply To The Sixth Amendment",
"I Will Always Give You The Truth I Will Never Lie To You In My music If You Cant Handle My Feelings And Emotions Please Unfollow Me",
"If There Is Bread Winners, There Is Bread Losers. But You Can\'t Toast What Isn\'t Real. #BreadPeopleLives",
"Most Trees Are Blue"
};
}
