public static class NoJaden{
public static string[] Phrases = {
"How Can Mirrors Be Real If We Aren't Real",
"How Can Windows Be Real If Our Eyes Aren't Real",
"How Can This Module Be Real If Our Eyes Aren't Real",
"I Am Not A Cyborg And I Don't Speak English",
"I Am Not A Mutant And I Don't Speak English",
"The Biggest Flex Anyone Will Ever Have Is Lying.",
"The Biggest Flex Anyone Will Ever Have Is Flying.",
"If A Cup Cake Falls From A Tree How Far Away Will It Be From Down. #Uranus",
"If A Cake Falls From A Tree How Far Away Will It Be From Down. #Jupiter",
"The More Time You Spend Asleep The More Time You Spend Asleep.",
"The More Time You Spend Awake The More Time You Spend Awake.",
"I Only Skate When I Have Physical Trauma",
"I Only Skate When I Have Psychological Trauma",
"A lot Of My Posts Will Come True In 2018",
"A lot Of My Tweets Will Come True In 2019",
"como os espelhos podem ser reais se olhos não são reais",
"como os espelhos podem reais se nossos olhos não são reais",
"Jealousy Just Reassures Your Envy.",
"Jealousy Just Reassures Your Rage.",
"You Do Not Know Who You Are Or Why Your Here So When You See Someone Who Does The Society Comes Together As A Whole And Destroys Them.",
"You Do Not Know Who You Are Or Why Your Here So When You See Someone Who Dose The Society Comes Together As A Whole And Obliterates Them.",
"To The Artist Of This Coming Generation And Of The Enlightenment. The People That Truly Understand Your Art are The People Who Don't Comment",
"To The Artist Of This Coming Generation And Of The Resurgence. The People That Truly Understand Your Art are The People Who Don't Comment",
"I Encourage You All To Unfollow Me So I Can Be Left With The People Who Actually Appreciate Philosophy And Poetry. #CoolTapeVol3",
"I Encourage You All To Unfollow Me So I Can Be Left With The People Who Actually Appreciate Poetry And Philosophy. #CoolTapeVol2",
"We Need To Stop Teaching The Youth About The Future And Encourage Them To Change The Past.",
"We Need To Stop Teaching The Youth About The Past And Encourage Them To Change The Present.",
"There Is No Nutrients In Our Food Anymore Or In Our Water OR IN OUR SOIL.",
"There Is No Nutrients In Our Soil Anymore Or In Our Food OR IN OUR WATER.",
"I Should Just Stop Tweeting, The Human Consciousness Must Raise Before I Speak My Juvenile Philosophy. Shouts Out To @NEWYORKTIMES",
"I Should Just Stop Tweeting, The Human Consciousness Must Raise Before I Speak My Juvenile Philosophy. Shouts Out To @God",
"Finding Nemo Is One Of The Greatest Movies Of All Time, Coachella.",
"The Great Gatsby Is One Of The Greatest Films Of All Time, Coachella.",
"Everybody Get Off Your Chair And Go Do What You Actually Wanna Do",
"Everybody Get Off Your Ass And Go Do What You Actually Wanna Do",
"If Everybody In The World Dropped Out Of College We Would Have A Much More Intelligent Society.",
"If Everybody In The World Dropped Out Of Windows We Would Have A Much More Intelligent Society.",
"If Newborn Babies Could Speak They Would Be The Most Dumb Beings On Planet Earth.",
"If Newborn Babies Could Speak They Would Be The Most Cringe Beings On Planet Earth.",
"Education Is Brainwash.",
"Education Is Death.",
"School Is The Medium To Brainwash The Youth.",
"School Is The Tool To Brainwash The Public.",
"People Use To Ask Me What Do You Want To Be When You Get Older And I Would Say What A Stupid Question The Real Question Is What Am I Right Now",
"People Use To Ask Me What Do You Wanna Be When You Get Older And I Would Say What A Dumb Question The Real Question Is What Am I Right Now",
"If A Book Store Never Runs Out Of A Certain Book, Dose That Mean That Everybody Reads It, Or Nobody Reads It",
"If A Book Store Never Runs Out Of A Certain Book, Does That Mean That Nobody Reads It, Or Everybody Reads It",
"\"It's Your Birthday\" Mateo Said. I Didn't Respond. \"Are You Not Excited To Be 15\" He Asked. Reading My Book I Uttered \"I Turned 21 Long Ago\"",
"\"It Is Your Birthday\" Mateo Said. I Didn't Respond. \"Are You Not Excited To Be 15\" He Asked. Reading My Book I Uttered \"I Turned 15 Long Ago\"",
"I Honestly Hate When People Love Even When There Close To You.",
"I Honestly Love When People Hate Even When They're Close To You.",
"Ill Never Forget The Posts That Believed In Me Since The Begging.",
"I\'ll Never Forget The Blogs That Believed In Me Since The Begging.",
"I Only Apply To The Second Amendment",
"I Only Apply To The Tenth Amendment",
"I Will Always Give You The Truth I Will Never Lie To You In My music If You Cant Handle My Feelings And Emotions Please Follow Me",
"I Will Always Give You The Lie I Will Never Lie To You In My music If You Cant Handle My Feelings And Emotions Please Unfollow Me",
"If There Are Bread Winners, There Are Bread Losers. But You Can\'t Toast What Isn\'t Real. #BreadPeopleLives",
"If There Is Bread Losers, There Is Bread Winners. But You Can\'t Toast What Isn\'t Real. #BreadPeopleLives",
"Most Trees Are Red",
"Most Tress Are Blue"
};
}
